### ISSUE TITLE
Annotation to attributes rector isn't complete

### ISSUE THREAD

**Issue by b1rdex** [rectorphp/rector-doctrine#116]
Hi! I found some problems using rector to transform annotations to attributes:

1. `@Index` must be moved out of `@Table` 
<img width="1595" alt="image" src="https://user-images.githubusercontent.com/312855/179762936-6da104f7-4cf4-4015-9660-7efec1eaf54d.png"> (Table attribute was deleted as it's not necessary anymore)

2. same for unique constraints 
<img width="1601" alt="image" src="https://user-images.githubusercontent.com/312855/179763191-31d148ca-5430-40a4-af0c-04910f2ddd28.png"> (Table attribute was deleted as it's not necessary anymore)

3. `@JoinTable` should be split 
<img width="1633" alt="image" src="https://user-images.githubusercontent.com/312855/179763429-0c1ed46c-82fa-4db4-9fd4-429af63b97ee.png">

I had to do these modifications manually after the initial rector run – these were not easy to find, partly because of silent BC by Doctrine.

I found some information about these in https://github.com/doctrine/orm/issues/9334#issuecomment-1022837964 and https://www.doctrine-project.org/projects/doctrine-orm/en/2.11/reference/attributes-reference.html

**Comment by TomasVotruba** [comment]
Hi @b1rdex ,

thanks for the report and git diffs. It really helped me to understand what needed to changed and how :slightly_smiling_face:  At start I got really confused by Doctrine docs, that suprisingly has no manual how to upgrade even basic annotations.

Instead of making the basic rule do too many things like before, we introduced a new rule `NestedAnnotationToAttributeRector` and move the nested annotation extract there: https://github.com/rectorphp/rector-src/pull/2781

That way we have 2 clean rules with separated jobs.

This is already deployed in latest `dev-main`. Any feedback from real project with Doctrine annotation is welcomed :+1:
